name: PyPi publication

on:
  push:
    tags:
      - '[0-9].[0-9].*' 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install python3-lxml
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 pds_github_util --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 pds_github_util --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Deploy locally
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -s
    - name: Create the package
      run: |
        pip install setuptools wheel
        rm -f dist/*
        python setup.py sdist bdist_wheel
    - name: Publish the Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.pypi_username }}
        password: ${{ secrets.pypi_password }}

